version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - .:/app
      - /app/frontend/node_modules
    working_dir: /app/frontend/
    command: npm install -y
    command: npm start
    network_mode: "host"
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile-backend
    working_dir: /api/backend
    command: bash -c "python /api/backend/api/manage.py makemigrations && python /api/backend/api/manage.py migrate && python /api/backend/api/manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/api
    ports: 
      - 8000:8000
    
